apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: db-1
  labels:
    env: dev
spec:
  replicas: 4
  selector:
    matchLabels:
      env: dev
      tier: db
  template:
    metadata:
      name: db
      labels:
        env: dev
        tier: db
    spec:
      containers:
        - name: busybox
          image: busybox
          command: ["sleep"]
          args: ["4800"]
