apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-demo-app
  labels:
    resource: deployment
    app: k8s-deep-dive-demo
spec:
  replicas: [SET REPLICA COUNT HERE]
  selector:
    matchLabels:
      app: k8s-deep-dive-demo
  template:
    metadata:
      labels:
        app: k8s-deep-dive-demo
    spec:
      containers:
      - name: k8s-deep-dive-demo
        image: [SET IMAGE NAME AND TAG HERE]
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-demo-service
  labels:
    resource: service
    app: k8s-deep-dive-demo
spec:
  selector:
    app: k8s-deep-dive-demo
  ports:
  - port: 5000
    targetPort: 80
  type: [SET LOAD BALANCER TYPE HERE]
