apiVersion: v1
kind: Service
metadata:
  name: [CREATE A SERVICE NAME]
  labels:
    app: wordpress
spec:
  ports:
    - port: 80
  selector:
    app: wordpress
    tier: frontend
  type: [CHOOSE APPROPRIATE SERVICE TYPE]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      containers:
      - image: wordpress:4.8-apache
        name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          value: [REFERENCE APPROPRIATE DNS NAME]
        - name: WORDPRESS_DB_USER
          value: root
        - name: WORDPRESS_DB_PASSWORD
          [CONFIGURE PASSWORD FROM SECRET]
        ports:
        - containerPort: 80
          name: wordpress
