apiVersion: v1
kind: Pod
metadata:
  name: myboot-demo
spec:
  containers:
    - name: myboot-demo-1
      image: docker.io/ssoutrs/myboot:v4
      volumeMounts:
        - mountPath: /tmp/demo
          name: demo-volume

    - name: myboot-demo-2
      image: docker.io/ssoutrs/myboot:v4

      env:
        - name: SERVER_PORT
          value: "8090"

      volumeMounts:
        - mountPath: /tmp/demo
          name: demo-volume

  volumes:
    - name: demo-volume
      emptyDir: {}
